### ISSUE TITLE
Feature Request: add keyboard shortcuts

### ISSUE THREAD

**Issue by TowelSniffer** [rooklift/nibbler#111]
it would be great to have keyboard shortcuts to load pgn and fen from the clipboard

**Comment by fohristiwhirl** [comment]
I'm running out of shortcuts.

For FEN you can just paste the FEN into the box and press return.

**Comment by TowelSniffer** [comment]
Yeah I do that but I find myself copying a lot of fen positions so a shortcut to copy to and paste from clipboard for fen would be a time saver, for me at least. How hard would it be to allow for custom shortcuts.

**Comment by fohristiwhirl** [comment]
> How hard would it be to allow for custom shortcuts.

I'm afraid that's the sort of feature creep I'm eager to avoid...

But if you want to edit the app for your own use, it's as simple as editing main.js (which, if you've downloaded a prebuilt app, you can find in the directory `resources/app` and adding an accelerator (see other accelerator lines there for the format)...

**Comment by TowelSniffer** [comment]
yeah, I should be able to figure it out thanks.

**Comment by inorick** [comment]
I had a look at how other tools support this (Chessbase, Jerry). How about supporting both FEN and PGN with the pasting shortcut Ctrl+V? If a valid FEN or PGN is found in the clipboard thrn the respective format can be imported. If not, nothing happens.
The nice thing about this is that Ctrl+V should probably not be mapped to any other feature anyway.
