### ISSUE TITLE
SyzygyPath with ceres

### ISSUE THREAD

**Issue by TowelSniffer** [rooklift/nibbler#127]
I can't get a Syzygy endgame tablebase to work with ceres. If I set a SyzygyPath in the JSON file, I get a message saying it found the dtz files but the analysis won't start. 

I was using the 3-4-5 tablebase from https://chess.massimilianogoi.com/download/tablebases/ 

It works well with Leela, and seems to work with ceres when using the command line, but I can't get it to work with ceres and nibbler together.

**Comment by fohristiwhirl** [comment]
Is there a space in the path?

**Comment by TowelSniffer** [comment]
there is but the issue persists with different paths. 

this is the message I get but it never starts analysing 
https://ibb.co/zNQQ5y0

**Comment by fohristiwhirl** [comment]
Oh right, yeah, tablebases are still broken when used in the configuration Nibbler uses.

I believe this will be fixed in Ceres 0.89, which is coming soonish.

**Comment by TowelSniffer** [comment]
ok that's good to hear, thanks for the info.

**Comment by fohristiwhirl** [comment]
It is, in fact, *not* fixed in 0.89.

But see https://github.com/dje-dev/Ceres/issues/38 for updates, maybe.

**Comment by rooklift** [comment]
I think it at least doesn't crash now, though Nibbler doesn't quite realise the response from Ceres contains useful info.
