### ISSUE TITLE
Engine halts abruptly while I'm analyzing a game

### ISSUE THREAD

**Issue by g0thmog** [rooklift/nibbler#142]
The engine gets "HALTED" quite a few times in between a game analysis in the latest update. How can I fix this issue? Thanks.

**Comment by rooklift** [comment]
Have you a node limit set in menu `Engine --> Node limit - normal` ?

**Comment by g0thmog** [comment]
Thanks for the speedy reply, rooklift. Yes, it's set to 10,000 currently.

**Comment by rooklift** [comment]
There was a sort of feature where Nibbler wouldn't change state when the engine stopped, and would resume the engine when changing position, but for various reasons this feature was becoming a nuisance. Its removal was deliberate I'm afraid, and I don't think I can really change my mind.

I suggest you set Unlimited or some higher value than 10,000.

**Comment by g0thmog** [comment]
Thanks a lot. Increasing the node limit fixed the issue.

**Comment by rooklift** [comment]
Note that hitting the limit will always cause the app to be in the halted state now. But as I say, this is basically intended, sorry.
