### ISSUE TITLE
Is there any way to downgrade nibbler or download an older version?

### ISSUE THREAD

**Issue by g0thmog** [rooklift/nibbler#143]
Hi, rooklift. Can we downgrade or download older versions (v1.8.1 or below to be specific)? The download files seem to be missing from the GitHub "releases" page. Thanks.

**Comment by rooklift** [comment]
Is this about the limit-based halting, or something else?

**Comment by g0thmog** [comment]
Yes, it's about limit-based halting.

**Comment by rooklift** [comment]
I'll add an option in the config file that will restore the old behaviour.

**Comment by rooklift** [comment]
Are you eager to have it now, or can you wait a day or so?

**Comment by g0thmog** [comment]
No problem. I can wait. Take your time, you have already pushed a lot of updates for us recently. Thanks again!

**Comment by rooklift** [comment]
OK, when the next version comes out, in the `Dev` menu there will be an item called `Allow stopped analysis`, toggle that.

**Comment by g0thmog** [comment]
Thanks. Waiting for the new version.

**Comment by rooklift** [comment]
Meh, I'll make it now, why not.
