### ISSUE TITLE
Pawns Moving Incorrectly

### ISSUE THREAD

**Issue by DrewDelong** [rooklift/nibbler#152]
Not sure if this is an actual issue with Nibbler or just something I'm doing wrong, but every time I try to load a game from FEN when playing as black the pawns always move in the wrong direction. I've uploaded a screenshot of what I'm seeing below:

[https://imgur.com/BZi11sR](https://imgur.com/BZi11sR )

Any Ideas? 

Great job on the project, I'm loving it so far!

**Comment by rooklift** [comment]
That's... interesting.

Post an example FEN?

**Comment by rooklift** [comment]
Although it requires checking, I would predict that your FEN is "the wrong way round". In other words, I suspect the position here is being seen from the white side, that there are black pawns on f2, g2, etc, and the engine (reasonably) is considering promoting them.

**Comment by rooklift** [comment]
The correct FEN for this position would be

`r2qkbnr/ppp2ppp/2n1p3/3p1bN1/5P2/2N4P/PPPPP1P1/R1BQKB1R b KQkq 0 1`

**Comment by DrewDelong** [comment]
@rooklift Seems as though you're right. I was using the FEN generator from [https://github.com/linrock/chessboard-recognizer](https://github.com/linrock/chessboard-recognizer), but after cross-referencing with other FEN generators it seems like this is just an issue with the aforementioned generator. 

Thank you!

**Comment by rooklift** [comment]
Perhaps there's some flag to tell it that the position is flipped?
