### ISSUE TITLE
Feature request:  Show winrates from Black's POV

### ISSUE THREAD

**Issue by primer-1** [rooklift/nibbler#157]
I like to play solitaire chess / analyze and see how the winrates change before and after each move by both sides.  This is most convenient when the stats are pegged to one side instead of relative to the side to move.  Right now this is easy to do as White but cumbersome as Black.

**Comment by rooklift** [comment]
While this is possible, it does increase the clunkiness of these options. Not sure if it's a desirable change overall.

**Comment by rooklift** [comment]
Well, I guess it's OK.
