### ISSUE TITLE
Problem Installing nibbler

### ISSUE THREAD

**Issue by dartffh** [rooklift/nibbler#162]
I wanted to install nibbler on my lenovo thinkpad x380 Yoga, so I downloaded nibbler and Lc0 (Newer non-NVidia GPUs ("only for latest versions of Windows 10" (since my laptop has an intelcore i5)). I then opened nibbler and it said this-
What do I do now and how do I fix it? If I am being stupid and making an obvious mistake please also tell me...
![Unbenannt](https://user-images.githubusercontent.com/80271216/123312425-9d560300-d528-11eb-9ce2-febfd4d3801a.PNG)

**Comment by rooklift** [comment]
I'm not entirely sure that's the right client - does your laptop have a GPU at all?

The exact error you've received though suggests Lc0 couldn't find its weights file (the neural net file). Usually its able to locate this automatically though, so it's odd.

**Comment by dartffh** [comment]
Okay so I now installed the newer cpu non gpu, and nibbler tells me that it is unable to load that engine

**Comment by rooklift** [comment]
What exactly happened?

**Comment by dartffh** [comment]
YES IT WORKS, FINALLY, tysm!

**Comment by dartffh** [comment]
My problem was that I didnt extract it from its winrar file because im stupid

**Comment by rooklift** [comment]
Alright well, good luck, remember performance will be quite bad without GPU, if you just want strength Stockfish will be much better.
