### ISSUE TITLE
I'd like to package a version of the app for mac

### ISSUE THREAD

**Issue by Jac-Zac** [rooklift/nibbler#163]
I'd like to also include lc0 and stockfish-14 as options and perhaps some different boards and pieces. And also I would love to use and icon which could be the one suggested recently. But I would need it to be 1024x1024. Would you guys be interested ? And also I think I can build a version for both arm64 and x86_64

**Comment by rooklift** [comment]
You're welcome to go ahead and try. First I'd suggest you see if you can get Nibbler to work in a standalone way where the engine is selected via the menu items (rather than being bundled in somehow).

**Comment by Jac-Zac** [comment]
I have made a version check it out [here](https://github.com/Jac-Zac/Nibbler_MacOS)

**Comment by Jac-Zac** [comment]
Btw I used the last icon that was proposed but I can change that in the future

**Comment by Jac-Zac** [comment]
I'll try to keep it up to date and make build for Apple Silicon and Intel Macs. If you would like me to change something pls tell me. Btw I used the icon that I have placed under assets/nibbler.icns, which is similar to the one that was suggested but with some changes

**Comment by rooklift** [comment]
I've added your project to the readme. I can't really try it or anything, I've no easy access to a Mac.
