### ISSUE TITLE
Bug/Feature request: Ability to scale the board size

### ISSUE THREAD

**Issue by AndrewTCEC** [rooklift/nibbler#166]
Great GUI, but I found somewhat of a major issue: the board size does not scale when you change the size of a window, at least since v2.1.7. Any help?
![image](https://user-images.githubusercontent.com/77082125/125954003-cd925142-3050-423d-8796-111ab110b352.png)

**Comment by rooklift** [comment]
It never did, not least because it's hard to anticipate how much space the user wants to leave for the various other stuff that's in the window. So I just let users explicitly set their board size, for which see the Sizes --> Board menu.

**Comment by AndrewTCEC** [comment]
Ok, I guess that works too @rooklift . Closing this then.
