### ISSUE TITLE
Nibbler doesn't send 'quit' to engine when closed

### ISSUE THREAD

**Issue by tsoj** [rooklift/nibbler#167]
When I close Nibbler it doesn't send a 'quit' command to loaded engines. This causes some engines to run at high CPU usage even after Nibbler is closed, such that I have to terminate them using a task manager.  
I am using Manjaro with Gnome. Nibbler version is 2.1.7.

**Comment by rooklift** [comment]
Thanks. I've just uploaded 2.1.8, see if it fixes it.

**Comment by tsoj** [comment]
> Thanks. I've just uploaded 2.1.8, see if it fixes it.

Thanks for the quick fix, works fine for me.
