### ISSUE TITLE
Self-play time limit

### ISSUE THREAD

**Issue by tsoj** [rooklift/nibbler#168]
I wanted to ask if there is a reason behind using node count as limit for searches and not move time (especially for self-play, play-as-white/black). The same nodecount value could have vastly different effects for different engines / engine configurations and different computer hardware, so I personally think that a move time limit would be more pleasant for the user.  
I think basically all UCI engines support a movetime argument, which works the same as the nodecount limit. So in terms of nibbler-code it would work pretty much the same as how it is done for nodecount limits.

Also, I wanted to say, that I am really enjoying this GUI :)

**Comment by rooklift** [comment]
Um, perhaps time is better, I dunno. Nibbler is somewhat primitive in terms of settings though (you'll have noticed the menu items that should really be sliders, etc), it will be slightly awkward to support both.

**Comment by tsoj** [comment]
I guess for Lc0 it might be preferable to have node limits, but if that doesn't matter I can submit a pull request where I replaced node limits with time limits.

**Comment by rooklift** [comment]
It's already sort of secretly present as a hidden setting that causes the node limit to be interpreted as a time limit instead. Currently the only way to get it is to go into the console at type

`config.use_movetime = true`

after which (for the rest of the session, but not permanently) the self-play node limit will be interpreted as the millisecond limit instead. This is dumb of course.
