### ISSUE TITLE
Provide a flatpak package for Linux

### ISSUE THREAD

**Issue by LongJohn-Silver** [rooklift/nibbler#169]
One of the biggest advantages in contrast with snaps, is that flatpaks are sandboxed, and therefore this results in a more secure and private experience since it is harder for some kind of malware to attack the system, or for said application to retrieve user information without them knowing it. Another good point is that everything that's uploaded to Flathub (Flatpak's team centralized repository). Just like snaps, Flatpaks are compatible with every distribution that supports it, so you don't have to be uploading different releases, and also is becoming a more standardized option for non-based and Ubuntu based distributions alike, being adopted already by twenty five flavours of Linux, and some of them come with flatpak preinstalled out of the box (CentOS, ElementaryOS, EndlessOS, Fedora, Linux Mint, PureOS and ZorinOS).

More information:

https://flathub.org/
https://flatpak.org/
https://flatpak.org/setup/
https://docs.flatpak.org/en/latest/

**Comment by LongJohn-Silver** [comment]
Could you at least gime me a reason why this was closed, @rooklift?

**Comment by rooklift** [comment]
You seemed to be spamming this in various repos.

**Comment by LongJohn-Silver** [comment]
I read the article Stockfish wrote about ChessBase violating their GPL 3 license and selling Stockfish with a different name, there they mentioned Leela Chess 0 (which I've never heard before), I visited their website and found this GUI, then when I visited this repo I found the Sabaki GUI which I also liked; after that you can see yesterday I also opened an issue in another Go project where I asked for Google dependencies to be removed. I like the idea of simplicity when installing behind flatpak, that's it. If you watch my profile carefully you'll see I'm not even a developer, I don't have anything to do with Flathub's team, I just install most of my applications this way.

If you don't have the time to provide another installation method, you hate flatpak for whatever reason or something else, I'll understand it, but please don't close this issue based merely on that, @rooklift.

**Comment by rooklift** [comment]
Well, I don't use Linux myself and really don't have the inclination to figure this out. If you find someone who wants to make it happen I probably wouldn't be opposed.

**Comment by LongJohn-Silver** [comment]
Fair enough, as I say I am not a developer so hopefully someone in the future will see this and might try to help.
