### ISSUE TITLE
Feature request: Add a default .desktop file

### ISSUE THREAD

**Issue by cyqsimon** [rooklift/nibbler#172]
Make life easier for the Linux folks. Here's an example:
`nibbler.desktop`
```
[Desktop Entry]
Categories=Game;BoardGame
Comment=Nibbler is a real-time analysis GUI for Leela Chess Zero (Lc0).
Exec=/usr/bin/nibbler
GenericName=Chess Analysis GUI
Icon=nibbler
Name=Nibbler
Path=/usr/bin
Terminal=false
Type=Application
```

Maybe consider finally adding an icon too? I do like this suggestion: https://github.com/rooklift/nibbler/issues/47#issuecomment-657897858

**Comment by bradydean** [comment]
Does Nibbler ship with an icon? I can't find one in the dist.

**Comment by rooklift** [comment]
It does not. Laziness on my part I guess. :)
