### ISSUE TITLE
engine.json

### ISSUE THREAD

**Issue by CantoroMC** [rooklift/nibbler#177]
When i click Engine>Choose engine... this error is raised
[100181:0928/120049.129836:ERROR:browser_main_loop.cc(269)] Gtk: gtk_native_dialog_run: assertion '!priv->visible' failed

Electron v14.0.1

In the meanwhile, someone can paste an example of engine.json, so that i can configure it  manually.
Thanks

**Comment by CantoroMC** [comment]
Sorry, for the disturb, I have been able to find an example by downloading the latest release for linux.
For anyone needing it:
	"pathToEngine": {
		"args": [],
		"options": {
			"MultiPV": 3
		},
		"search_nodes": null,
		"search_nodes_special": 10000000,
		"limit_by_time": false
	}

**Comment by rooklift** [comment]
Hi - I've opened a new issue #178 for the GTK thing.
