### ISSUE TITLE
Backwards analysis

### ISSUE THREAD

**Issue by dav1312** [rooklift/nibbler#186]
Have an option to auto-evaluate from the end of the game to the beginning

**Comment by rooklift** [comment]
I think I can probably add this fairly easily - what engines benefit from doing it this way, btw? I know Stockfish can get some benefit, do other engines also?

**Comment by dav1312** [comment]
Not sure which ones benefit from it specifically I just asked for stockfish 😅

**Comment by rooklift** [comment]
It's in the code now, I dunno if you want to try it out (and tell me if it seems to work correctly) or just wait for a release?

**Comment by dav1312** [comment]
It seems to be working fine 😄
Maybe add a shortcut like `Ctrl+F12` or `Shift+F12`?

**Comment by rooklift** [comment]
I chose Shift.
