### ISSUE TITLE
Change defaults

### ISSUE THREAD

**Issue by dav1312** [rooklift/nibbler#187]
- Centipawn POV > White
  - I think everyone is already used to see it this way, positive for white, negative for black.
- Win / draw / loss POV > White
  - This is a personal preference. W for white and L for black.
- Linebreak before stats > Enabled
  - Easier to see, stays in the same place even if depth increases.
- Always show actual move (if known) > Enabled
- ...with outline > Enabled

**Comment by rooklift** [comment]
Well - I've made the choices that I've made, I think having the options is the main thing.
