### ISSUE TITLE
Custom position with Nibbler?

### ISSUE THREAD

**Issue by EnterYourNickname** [rooklift/nibbler#188]
I see that we can copy and paste FEN below but thats not what I am looking for.

My query is simple: I want to edit the game with custom position and instruct the engine to play white/black from that position. How do I do it via Nibbler?

**Comment by rooklift** [comment]
I never got around to implementing this.

**Comment by ihavenonickname** [comment]
I use https://www.chess.com/analysis to setup the board, then copy the FEN string and paste it into Nibbler. 

I'd love to be able to setup the board inside Nibbler.

**Comment by rooklift** [comment]
I know - but it's not trivial to implement and I don't know if / when I'll find the time, if ever.
