### ISSUE TITLE
Add show threat function

### ISSUE THREAD

**Issue by Kiiro1** [rooklift/nibbler#199]
The easiest way that's comes to my mind, let's say its white to move and black has a threat, you just overwrite position as black to move and engine shows the move.

**Comment by rooklift** [comment]
It sounds simple but there's a lot of logic involved and previously-true assumptions being broken.

It's on the [list of suggestions](https://github.com/rooklift/nibbler/issues/10) but realistically I'm not very likely to get around to this any time soon.
