### ISSUE TITLE
Move Display

### ISSUE THREAD

**Issue by cwmraig** [rooklift/nibbler#200]
How do I get a move history or pgn file to display the moves in Nibbler. Screen shots and videos show these moves on the bottom
of the nibbler window but I can't get them to appear.

**Comment by rooklift** [comment]
I think the only reason it wouldn't be visible is if the window size is too small for it to fit. You can either increase the size of the window, or decrease the size of the board via the Sizes menu.

**Comment by cwmraig** [comment]
Thanks . Feel such an idiot reducing boardsize did the trick

**Comment by rooklift** [comment]
Nah, the way Nibbler deals with sizes is kind of user-unfriendly to be honest.
