### ISSUE TITLE
Nibbler with new leela  v0.29 doesnt work

### ISSUE THREAD

**Issue by Vukica14** [rooklift/nibbler#203]
Hi to all,
most recent nibbler v2,36 doesn't work with Leela  v0.29 as nibbler showing "stopped, halt, null".

What could be a reason? Otherwise I performed benchmark on leela and works well. I have Win7 x64.

Many thanks in advance.

**Comment by Vukica14** [comment]
Also I tried to install stockfish_15_x64_popcnt but doesn't work as well with the same error message except "null" now is "ucinewgame"

**Comment by rooklift** [comment]
> "stopped, halt, null"

This would typically suggest Lc0 didn't launch at all. My first guess would be that the location of lc0 changed on your system? If so, you'd need to find it again via `Engine --> Choose engine...`

> stockfish_15_x64_popcnt but doesn't work as well with the same error message except "null" now is "ucinewgame"

That sounds like a totally normal startup for Stockfish. Did it actually fail to do anything when you tried to analyse?

btw from your description you've got the dev option "show engine state" selected which I wouldn't really recommend for normal use.

**Comment by Vukica14** [comment]
Hi and thanks for the answer! I try to do so Engine --> Choose engine.. but it didnt work. And stockfish also doesn't analyze. Any idea what could be wrong?

**Comment by rooklift** [comment]
It's quite mysterious.

If you open Leela by double clicking it in Windows, and type in `go infinite`, does it run?

One thing you could try is enabling Nibbler's logfile (see Dev menu) and posting a sample log here.

**Comment by Vukica14** [comment]
Hi again and thanks again :-D
Leela is working well. 
Nibbler log file is here:
========================================
Nibbler startup at Tue, 30 Aug 2022 05:49:36 GMT

Launching D:\_LeelaZero\lc0v0.29.0\lc0.exe

(failed) --> uci
(failed) --> quit
