### ISSUE TITLE
Auto-eval disables on its own?

### ISSUE THREAD

**Issue by mvrozanti** [rooklift/nibbler#209]
With arrows turned on, after starting a new game, when you auto-evaluate line many arrows show up. After selecting a move however you have to trigger auto-evaluate line again in order to show other moves than the best ones. Is this expected behavior, and is this configurable? Thanks

edit: I'm running Lc0 v0.30.0-dev+git.ea139e4 on nibbler version 2.3.8.

**Comment by mvrozanti** [comment]
Got that behavior with "Always show actual move (if known)" option.

**Comment by rooklift** [comment]
"Auto-evaluate line" is for when a whole game exists - it looks at one position then goes onto the next position and continues, etc.

If you want to do "live" analysis while moving about, normally you would instead just select "Go".

**Comment by mvrozanti** [comment]
Can I have it automatically go after each move? Otherwise you still need to trigger Go to show more arrows

**Comment by rooklift** [comment]
I think that should happen if you either:

* Adjust `Limit --> Normal` to a high enough number that you don't reach it, or
* Adjust `Dev --> Hacks and Kludges --> Allow stopped analysis` to be **on**.

**Comment by mvrozanti** [comment]
That works! Thanks a lot!
