### ISSUE TITLE
Nodes per second; node limit halts analysis after limit reached. 

### ISSUE THREAD

**Issue by iftikharramnandan** [rooklift/nibbler#223]
Hello! I was wondering if there is a feature similar to Arena where you can set the nodes per second; the problem with just setting a node limit is that the analysis halts when node limit has been hit, and I keep having to press go in order to get new analysis. Does nodes per second exist so that I don't have to click go after every halt; or is there a way to make it not halt without doing unlimited/ no node limit?

**Comment by rooklift** [comment]
Try this:

* Open Nibbler
* Click Dev --> Show engines.json
* Close Nibbler -- important!
* Open engines.json in a text editor.
* There should be a line that has `"args": [],`
* Replace that with "args": `["--nps-limit=200"],`

(Or some other value than 200,  whatever you like.

**Comment by iftikharramnandan** [comment]
Thanks. Resolved.
