### ISSUE TITLE
Nibbler v2.4.0 - Lc0 v0.29 "Awaiting uciok from engine"

### ISSUE THREAD

**Issue by Saphircelestial** [rooklift/nibbler#225]
Checked openblas, dnnl and opencl. The engine could not launch.
OS:
Edition	Windows 10 Home
Version	22H2
Installed on   ‎ 3/‎4/‎2023
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by Saphircelestial** [comment]
Ps. There was no problem with other engines or functionality of the program.

**Comment by rooklift** [comment]
Hmm. So to be clear: Nibbler can run Stockfish (or something) but not Lc0?

Can you confirm Lc0 works if you launch it by itself?

**Comment by Saphircelestial** [comment]
lco does not work. now I checked Roden IV 64x and does not work unless you put him in fn + 11 (self-play), Roden IV plain works unless you will change threads or ram, itd.
Other than that stockfish works as it should be with no problems whatsoever.

**Comment by rooklift** [comment]
But does Lc0 work if you just directly double-click it?

**Comment by Saphircelestial** [comment]
I mean the engine "crashes" when I launch it.

**Comment by rooklift** [comment]
That happens when not using Nibbler at all?

**Comment by Saphircelestial** [comment]
wait a minute

**Comment by Saphircelestial** [comment]
![image](https://user-images.githubusercontent.com/127032488/222968357-a8bf2f0a-e08c-4589-a25a-b01b692e7574.png)
It seems like something is missing I guess

**Comment by rooklift** [comment]
Well it seems to be an Lc0 issue, not a Nibbler issue.
