### ISSUE TITLE
Eval on nibbler from stockfish

### ISSUE THREAD

**Issue by DARKLORD1010** [rooklift/nibbler#226]
How can I get eval that stockfish give in nibbler chess gui for each move?

**Comment by rooklift** [comment]
Engines like Stockfish really lose strength drastically if they try to analyse every move (because it takes vastly longer). This is true of Lc0 too but to a lesser extent. Anyway, the upshot is that engines like Stockfish really don't support that well.

**Comment by DARKLORD1010** [comment]
I am talking about this one https://github.com/official-stockfish/Stockfish/wiki/Commands#:~:text=Example-,eval,-Display%20the%20static can't i get it on nibbler chess guia

**Comment by rooklift** [comment]
Ah, then I'm afraid the answer is no.
