### ISSUE TITLE
Stockfish support, extent?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [rooklift/nibbler#234]
> These days, Nibbler more-or-less works with traditional engines like [Stockfish](https://stockfishchess.org/), too.

What's "more-or-less"? What's it lack compared to Leela?

Can it replicate Lichess's `Request a Computer Analysis` feature? That is, given a PGN, **(1)** produce a win odds graph, **(2)** label moves as inaccuracy/mistake/blunder, **(3)** do focused evaluation on the move being observed, **(4)** ability to branch out in analysis board? See e.g. [this game](https://lichess.org/hQGjNKkZ/black):

![image](https://github.com/rooklift/nibbler/assets/16495490/7a411e12-c403-46bc-9e52-ad56d3262aab)

**Comment by rooklift** [comment]
Nibbler is fairly basic, it can make a graph but won't explicitly label mistakes (though those will be fairly obvious from the graph swings). This is true regardless of using Leela / Stockfish. It can evaluation positions / moves but is strictly one board at a time.

**Comment by yuzisee** [comment]
For what it's worth, Lichess uses https://github.com/lichess-org/lila/pull/5337/commits/133a1ebe761c4a37debc64cdaa8371e8580a1c5d to distinguish between inaccuracy/mistake/blunder
