### ISSUE TITLE
What should the evaluation graph be?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [rooklift/nibbler#245]
Continuation of: from https://github.com/rooklift/nibbler/issues/242#issuecomment-1715520110 to https://github.com/rooklift/nibbler/issues/242#issuecomment-1720768889

TL;DR handling differences in engine evaluations; determining the best "for-humans" evaluation (and blunders-etc labeling of)

**Comment by yuzisee** [comment]
Looks like a decision has been made: #244 

- https://github.com/rooklift/nibbler/pull/235 has been updated accordingly
