### ISSUE TITLE
set the limite Nodes manualy

### ISSUE THREAD

**Issue by Lunestre** [rooklift/nibbler#253]
When i try to set up the nodes limite, we the the choises 1000 10k, 100k...
It there a file where this list is define?

An other choise could be to a a form where you can set the number you want (from 100 to  100 000 000 ).
In my case, with my setup, 1500, 5000 and 15 000 are both choise i wanted to have.

**Comment by rooklift** [comment]
The options can be changed in the Ogatak config file. You can find this via `Dev --> Show config file`

Note that you should NOT edit it while Ogatak is running (or your changes will be lost).

**Comment by Lunestre** [comment]
Thx a lot. This is what i was searching

**Comment by rooklift** [comment]
Actually - now that I think about it, this only affects what you get when changing the nodes via the "Up slightly" and "Down slightly" options. The menu items are hardcoded.

**Comment by Lunestre** [comment]
hello.
Thanks for the tips. I made the change for my local analysis.
Thanks a lot!
