### ISSUE TITLE
Using lichess PGN copy to clipboard button ends in an Alert in the application

### ISSUE THREAD

**Issue by Hypenate** [rooklift/nibbler#267]
When using the copy/paste button from Lichess, the applicaton throws an alert:
![image](https://github.com/user-attachments/assets/e7398299-189d-4bf1-b26f-0c95f6860c13)
results in:
![image](https://github.com/user-attachments/assets/8b609e8c-5815-424c-83bb-9366f195d747)

Manually copy pasting works as intended.

**Comment by rooklift** [comment]
Looks like Lichess copies a link to the clipboard, rather than the PGN itself?

**Comment by Hypenate** [comment]
Oops, I should've checked before assuming 😲.
