### ISSUE TITLE
How to use two or more GPUs 

### ISSUE THREAD

**Issue by Nordlandia** [rooklift/nibbler#68]
How do i analyse with two cards. I tried adjusting settings but wrong syntax.

**Comment by fohristiwhirl** [comment]
I honestly don't know, but Nibbler can send arbitrary UCI or command-line options; you can configure this with the `config.json` file, which you can discover via the App menu.

**Comment by Nordlandia** [comment]
I tried edit json. 

"BackendOptions": "(backend=cudnn-fp16,gpu=0),(backend=cudnn-fp16,gpu=1)",

Didn't work.

**Comment by fohristiwhirl** [comment]
Supposedly the recommended configuration is:

```
"Backend": "multiplexing",
"BackendOptions: "backend=cudnn-fp16,(gpu=0),(gpu=1)",
"Threads": 3
```

**Comment by Nordlandia** [comment]
I tried, i can't see second GPU under load in task manager.

**Comment by fohristiwhirl** [comment]
Are you able to use 2 GPUs outside of Nibbler?

**Comment by Nordlandia** [comment]
Yes i am able. In Fritz interface and in Cutechess GUI. 

(backend=cudnn-fp16,gpu=0),(backend=cudnn-fp16,gpu=1)

**Comment by fohristiwhirl** [comment]
Someone reported success here:

http://talkchess.com/forum3/viewtopic.php?p=843880#p843880
