### ISSUE TITLE
CSS needs improved

### ISSUE THREAD

**Issue by rooklift** [rooklift/nibbler#83]
The general layout of Nibbler is like this:

![nibbler_layout](https://user-images.githubusercontent.com/16438795/80288060-3de64280-872d-11ea-821c-8c9feae7d6c3.png)

But I struggle to get the CSS right. Especially, the bottom of the graphbox needs to line up with the bottom of the board - currently this is done by using JS to calculate the correct height of the infobox and setting it exactly, so that the graph below it lines up "by magic".

Is there no better way?

**Comment by ColinCee** [comment]
If you want to do something like this, I would recommend using flex box css rules.

It can be a can of worms to get started though, however using flexbox it will be responsive and you won't need js

**Comment by CiriousJoker** [comment]
I'd love to help here, but I'm busy with exams atm. I think I can take a look at this in a month or so.

**Comment by rooklift** [comment]
Perhaps CSS grid would work, with layout like

```
a b
a c
a d
e e
f f
```
